// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJaBmxbs2mPfyCQjfkwcu6-nEKH7liKqg',
    appId: '1:893573966257:web:3d6181d202125fe53bb590',
    messagingSenderId: '893573966257',
    projectId: 'mobileappsauvignon',
    authDomain: 'mobileappsauvignon.firebaseapp.com',
    storageBucket: 'mobileappsauvignon.appspot.com',
    measurementId: 'G-LHZRBSCE5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHeWqJDmcB4qiNR0t95fM7TKpuDlP34uo',
    appId: '1:893573966257:android:562f0f559dfaa8443bb590',
    messagingSenderId: '893573966257',
    projectId: 'mobileappsauvignon',
    storageBucket: 'mobileappsauvignon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsF7LtUXDfIR-4jGXtI1ZcvydIq9RaHa4',
    appId: '1:893573966257:ios:f974810c69d557783bb590',
    messagingSenderId: '893573966257',
    projectId: 'mobileappsauvignon',
    storageBucket: 'mobileappsauvignon.appspot.com',
    iosBundleId: 'com.example.flutterFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsF7LtUXDfIR-4jGXtI1ZcvydIq9RaHa4',
    appId: '1:893573966257:ios:210597ed3c8a72583bb590',
    messagingSenderId: '893573966257',
    projectId: 'mobileappsauvignon',
    storageBucket: 'mobileappsauvignon.appspot.com',
    iosBundleId: 'com.example.flutterFirstApp.RunnerTests',
  );
}
